name: Monthly reviews refresh

on:
  schedule:
    # Todo dia 26 às 03:00 UTC (00:00 em Brasília)
    - cron: "0 3 26 * *"
  workflow_dispatch: {}

env:
  SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  # Limites de custo (opcionais, lidos pelo baixar_reviews.py)
  MAX_NEW: "60"                 # teto de reviews novos por execução
  OLD_STREAK_STOP_AT: "5"       # para após 5 IDs antigos seguidos
  PAGE_SLEEP: "0.8"
  RETRY_SLEEP: "2.0"
  MAX_RETRIES: "5"

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (download -> classify -> merge)
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MAX_NEW: ${{ env.MAX_NEW }}
          OLD_STREAK_STOP_AT: ${{ env.OLD_STREAK_STOP_AT }}
          PAGE_SLEEP: ${{ env.PAGE_SLEEP }}
          RETRY_SLEEP: ${{ env.RETRY_SLEEP }}
          MAX_RETRIES: ${{ env.MAX_RETRIES }}
        run: |
          python run_all.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "chore(data): monthly refresh reviews"
            git push
          else
            echo "Nada para commitar."
          fi
